# Generated by Django 4.2.5 on 2023-11-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oldstudents', '0003_rename_field_of_study_student_field_of_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='media'),
        ),
    ]
