# Generated by Django 4.2.5 on 2023-11-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oldstudents', '0006_student_year_of_completion_student_year_of_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='field_of_work',
            field=models.CharField(choices=[('Business', 'Business'), ('Education', 'Education'), ('Industrialization', 'Industrialization'), ('Public Servant', 'Public Servant'), ('Lawyers', 'Lawyers'), ('Fishing', 'Fishing')], max_length=20),
        ),
    ]
